export const DEFAULT_WEAPON_POOL = [
    { id: 'sword_iron', name: '铁刃长剑', type: 'SWORD', rarity: 'COMMON', icon: '⚔️', range: 1, apCost: 3, damageMin: 7, damageMax: 9 },
    { id: 'sword_knight', name: '骑士佩剑', type: 'SWORD', rarity: 'RARE', icon: '⚔️', range: 1, apCost: 3, damageMin: 8, damageMax: 11 },
    { id: 'sword_moon', name: '月影细刃', type: 'SWORD', rarity: 'LEGENDARY', icon: '⚔️', range: 1, apCost: 3, damageMin: 9, damageMax: 12 },
    { id: 'sword_frost', name: '霜刃长剑', type: 'SWORD', rarity: 'COMMON', icon: '⚔️', range: 1, apCost: 3, damageMin: 7, damageMax: 10 },
    { id: 'sword_sun', name: '曙光之刃', type: 'SWORD', rarity: 'EPIC', icon: '⚔️', range: 1, apCost: 3, damageMin: 8, damageMax: 12 },
    { id: 'sword_dragon', name: '龙纹钢剑', type: 'SWORD', rarity: 'EPIC', icon: '⚔️', range: 1, apCost: 3, damageMin: 9, damageMax: 11 },
    { id: 'sword_shadow', name: '影舞短剑', type: 'SWORD', rarity: 'RARE', icon: '⚔️', range: 1, apCost: 3, damageMin: 7, damageMax: 11 },
    { id: 'sword_ember', name: '烬火双刃', type: 'SWORD', rarity: 'ENEMY', icon: '⚔️', range: 1, apCost: 3, damageMin: 10, damageMax: 12 },
    { id: 'spear_bronze', name: '青铜长枪', type: 'SPEAR', rarity: 'COMMON', icon: '🔱', range: 2, apCost: 4, damageMin: 5, damageMax: 8 },
    { id: 'spear_guard', name: '守卫枪', type: 'SPEAR', rarity: 'RARE', icon: '🔱', range: 2, apCost: 4, damageMin: 6, damageMax: 9 },
    { id: 'spear_storm', name: '风暴突刺枪', type: 'SPEAR', rarity: 'EPIC', icon: '🔱', range: 2, apCost: 4, damageMin: 7, damageMax: 10 },
    { id: 'spear_frost', name: '霜锋长枪', type: 'SPEAR', rarity: 'COMMON', icon: '🔱', range: 2, apCost: 4, damageMin: 5, damageMax: 9 },
    { id: 'spear_royal', name: '王庭骑枪', type: 'SPEAR', rarity: 'LEGENDARY', icon: '🔱', range: 2, apCost: 4, damageMin: 6, damageMax: 10 },
    { id: 'spear_hawk', name: '苍鹰长枪', type: 'SPEAR', rarity: 'RARE', icon: '🔱', range: 2, apCost: 4, damageMin: 7, damageMax: 9 },
    { id: 'spear_meteor', name: '流星突刺枪', type: 'SPEAR', rarity: 'ENEMY', icon: '🔱', range: 2, apCost: 4, damageMin: 8, damageMax: 10 },
    { id: 'spear_tide', name: '潮汐长枪', type: 'SPEAR', rarity: 'EPIC', icon: '🔱', range: 2, apCost: 4, damageMin: 5, damageMax: 10 },
    { id: 'bow_oak', name: '橡木短弓', type: 'BOW', rarity: 'COMMON', icon: '🏹', range: 3, apCost: 4, damageMin: 4, damageMax: 7 },
    { id: 'bow_hunter', name: '猎手长弓', type: 'BOW', rarity: 'RARE', icon: '🏹', range: 3, apCost: 4, damageMin: 5, damageMax: 8 },
    { id: 'bow_star', name: '星辉连弓', type: 'BOW', rarity: 'EPIC', icon: '🏹', range: 3, apCost: 4, damageMin: 6, damageMax: 9 },
    { id: 'bow_frost', name: '霜叶长弓', type: 'BOW', rarity: 'COMMON', icon: '🏹', range: 3, apCost: 4, damageMin: 4, damageMax: 8 },
    { id: 'bow_wind', name: '疾风猎弓', type: 'BOW', rarity: 'EPIC', icon: '🏹', range: 3, apCost: 4, damageMin: 5, damageMax: 9 },
    { id: 'bow_sand', name: '沙原曲弓', type: 'BOW', rarity: 'RARE', icon: '🏹', range: 3, apCost: 4, damageMin: 6, damageMax: 8 },
    { id: 'bow_twilight', name: '暮光重弓', type: 'BOW', rarity: 'LEGENDARY', icon: '🏹', range: 3, apCost: 4, damageMin: 7, damageMax: 9 },
    { id: 'bow_ranger', name: '游侠之弓', type: 'BOW', rarity: 'ENEMY', icon: '🏹', range: 3, apCost: 4, damageMin: 4, damageMax: 9 }
];
